# Generated by Django 4.0 on 2021-12-31 13:42

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='active',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='roll',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='thumb',
        ),
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='country',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='manager',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='turnover',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Personal_Picture',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='customuser',
            name='annual_off_days',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='customuser',
            name='days_remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='days_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='experience',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nationality',
            field=models.CharField(blank=True, choices=[('Afghan', 'Afghan'), ('Albanian', 'Albanian'), ('Algerian', 'Algerian'), ('Argentinian', 'Argentinian'), ('Australian', 'Australian'), ('Bangladeshi', 'Bangladeshi'), ('Belgian', 'Belgian'), ('Bolivian', 'Bolivian'), ('Batswana', 'Batswana'), ('Brazilian', 'Brazilian'), ('Bulgarian', 'Bulgarian'), ('Cambodian', 'Cambodian'), ('Cameroonian', 'Cameroonian'), ('Canadian', 'Canadian'), ('Chilean', 'Chilean'), ('Chinese', 'Chinese'), ('Colombian', 'Colombian'), ('Costa Rican', 'Costa Rican'), ('Croatian', 'Croatian'), ('Cuban', 'Cuban'), ('Czech', 'Czech'), ('Danish', 'Danish'), ('Dominican', 'Dominican'), ('Ecuadorian', 'Ecuadorian'), ('Egyptian', 'Egyptian'), ('Salvadorian', 'Salvadorian'), ('English', 'English'), ('Estonian', 'Estonian'), ('Ethiopian', 'Ethiopian'), ('Fijian', 'Fijian'), ('Finnish', 'Finnish'), ('French', 'French'), ('German', 'German'), ('Ghanaian', 'Ghanaian'), ('Greek', 'Greek'), ('Guatemalan', 'Guatemalan'), ('Haitian', 'Haitian'), ('Honduran', 'Honduran'), ('Hungarian', 'Hungarian'), ('Icelandic', 'Icelandic'), ('Indian', 'Indian'), ('Indonesian', 'Indonesian'), ('Iranian', 'Iranian'), ('Iraqi', 'Iraqi'), ('Irish', 'Irish'), ('Italian', 'Italian'), ('Jamaican', 'Jamaican'), ('Japanese', 'Japanese'), ('Jordanian', 'Jordanian'), ('Kenyan', 'Kenyan'), ('Kuwaiti', 'Kuwaiti'), ('Lao', 'Lao'), ('Latvian', 'Latvian'), ('Lebanese', 'Lebanese'), ('Libyan', 'Libyan'), ('Lithuanian', 'Lithuanian'), ('Malagasy', 'Malagasy'), ('Malaysian', 'Malaysian'), ('Malian', 'Malian'), ('Maltese', 'Maltese'), ('Mexican', 'Mexican'), ('Mongolian', 'Mongolian'), ('Moroccan', 'Moroccan'), ('Mozambican', 'Mozambican'), ('Namibian', 'Namibian'), ('Nepalese', 'Nepalese'), ('Dutch', 'Dutch'), ('New Zealand', 'New Zealand'), ('Nicaraguan', 'Nicaraguan'), ('Nigerian', 'Nigerian'), ('Norwegian', 'Norwegian'), ('Pakistani', 'Pakistani'), ('Panamanian', 'Panamanian'), ('Paraguayan', 'Paraguayan'), ('Peruvian', 'Peruvian'), ('Philippine', 'Philippine'), ('Polish', 'Polish'), ('Portuguese', 'Portuguese'), ('Romanian', 'Romanian'), ('Russian', 'Russian'), ('Saudi', 'Saudi'), ('Scottish', 'Scottish'), ('Senegalese', 'Senegalese'), ('Serbian', 'Serbian'), ('Singaporean', 'Singaporean'), ('Slovak', 'Slovak'), ('South African', 'South African'), ('Korean', 'Korean'), ('Spanish', 'Spanish'), ('Sri Lankan', 'Sri Lankan'), ('Sudanese', 'Sudanese'), ('Swedish', 'Swedish'), ('Swiss', 'Swiss'), ('Syrian', 'Syrian'), ('Taiwanese', 'Taiwanese'), ('Tajikistani', 'Tajikistani'), ('Thai', 'Thai'), ('Tongan', 'Tongan'), ('Tunisian', 'Tunisian'), ('Turkish', 'Turkish'), ('Ukrainian', 'Ukrainian'), ('Emirati', 'Emirati'), ('British', 'British'), ('American', 'American'), ('Uruguayan', 'Uruguayan'), ('Venezuelan', 'Venezuelan'), ('Vietnamese', 'Vietnamese'), ('Welsh', 'Welsh'), ('Zambian', 'Zambian'), ('Zimbabwean', 'Zimbabwean')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('HR', 'HR'), ('Branch Manager', 'Branch Manager'), ('Department Manager', 'Department Manager'), ('Software Engineer', 'Software Engineer'), ('Senior Software Engineer', 'Senior Software Engineer'), ('Full Stack Developer', 'Senior Software Engineer'), ('FrontEnd Developer', 'FrontEnd Developer'), ('BackEnd Developer', 'BackEnd Developer'), ('Python Developer', 'Python Developer'), ('UX Designer', 'UX Designer'), ('UI Designer', 'UI Designer'), ('DOTnet Developer', 'DOTnet Developer'), ('Java Developer', 'Java Developer'), ('Android Developer', 'Android Developer'), ('Mobile Developer', 'Mobile Developer'), ('Project Development Manager', 'Project Development Manager'), ('Chief Operating Officer', 'Chief Operating Officer'), ('Digital Marketing', 'Digital Marketing'), ('Marketing Officer', 'Marketing Officer'), ('Databace Administrator', 'Databace Administrator'), ('Quality Assurance', 'Quality Assurance'), ('Junior Frontend Developer', 'Junior Frontend Developer'), ('Trainee', 'Trainee')], default='HR', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='work_type',
            field=models.CharField(blank=True, choices=[('On Site', 'On Site'), ('Remote', 'Remote')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.branch'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='salary',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('50000'), default_currency='USD', max_digits=14),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Managment', 'Managment'), ('Development', 'Development'), ('Testing', 'Testing'), ('Quality', 'Quality')], max_length=50),
        ),
    ]
