# Generated by Django 3.1.7 on 2022-01-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hours_remaining',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hours_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='monthly_permission_hours',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(blank=True, default=20220105, max_length=255, null=True),
        ),
    ]
