# Generated by Django 4.0 on 2021-12-31 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_active_remove_customuser_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='manager',
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_manager',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='department',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='department',
            name='department_manager',
            field=models.CharField(default='', max_length=50),
        ),
    ]
