# Generated by Django 4.0 on 2021-12-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_branch_manager_branch_branch_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='salary_currency',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='salary',
            field=models.FloatField(default='50000'),
        ),
    ]
