# Generated by Django 4.0 on 2021-12-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_salary_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('HR', 'HR'), ('Branch Manager', 'Branch Manager'), ('Department Manager', 'Department Manager'), ('Software Engineer', 'Software Engineer'), ('Senior Software Engineer', 'Senior Software Engineer'), ('Full Stack Developer', 'Senior Software Engineer'), ('FrontEnd Developer', 'FrontEnd Developer'), ('BackEnd Developer', 'BackEnd Developer'), ('Python Developer', 'Python Developer'), ('UX Designer', 'UX Designer'), ('UI Designer', 'UI Designer'), ('DOTnet Developer', 'DOTnet Developer'), ('Java Developer', 'Java Developer'), ('Android Developer', 'Android Developer'), ('Mobile Developer', 'Mobile Developer'), ('Project Development Manager', 'Project Development Manager'), ('Chief Operating Officer', 'Chief Operating Officer'), ('Digital Marketing', 'Digital Marketing'), ('Marketing Officer', 'Marketing Officer'), ('Databace Administrator', 'Databace Administrator'), ('Quality Assurance', 'Quality Assurance'), ('Junior Frontend Developer', 'Junior Frontend Developer'), ('Trainee', 'Trainee')], default='HR', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='salary',
            field=models.FloatField(blank=True, default='50000', null=True),
        ),
    ]
