# Generated by Django 4.0 on 2022-01-01 11:59

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_branch_city_alter_branch_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='joined',
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, choices=[('Managment', 'Managment'), ('Development', 'Development'), ('Testing', 'Testing'), ('Quality', 'Quality')], max_length=50, null=True),
        ),
    ]
