# Generated by Django 4.0 on 2021-12-31 23:02

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_branch_city_alter_branch_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
