# Generated by Django 4.0 on 2021-12-31 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_branch_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, choices=[('Managment', 'Managment'), ('Development', 'Development'), ('Testing', 'Testing'), ('Quality', 'Quality')], max_length=50, null=True),
        ),
    ]
