# Generated by Django 4.0 on 2022-01-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customuser_joined_alter_branch_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Personal_Picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
