# Generated by Django 4.0 on 2022-01-01 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_branch_name_alter_department_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='joined',
        ),
    ]
