# Generated by Django 4.0 on 2022-01-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_personal_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married')], max_length=50, null=True),
        ),
    ]
