# Generated by Django 4.0 on 2022-01-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(blank=True, default={'20220102'}, max_length=255, null=True),
        ),
    ]
