# Generated by Django 4.0 on 2022-01-03 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=50, null=True)),
                ('joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('request_status', models.CharField(default='Pending', max_length=50)),
                ('hours', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='hours_remaining',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hours_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='monthly_permission_hours',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='days_remaining',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(blank=True, default=20220103, max_length=255, null=True),
        ),
    ]
