# Generated by Django 4.0 on 2022-01-03 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_leave_customuser_hours_remaining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customuser'),
        ),
    ]
