# Generated by Django 4.0 on 2022-01-03 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_leave_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='branch_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.branch'),
        ),
    ]
