# Generated by Django 4.0 on 2022-01-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_employee_id_alter_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Personal_Picture',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
