# Generated by Django 4.0 on 2022-01-03 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_leave_branch_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='joined',
            new_name='date',
        ),
    ]
