# Generated by Django 4.0 on 2022-01-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_customuser_personal_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Personal_Picture',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
