# Generated by Django 4.0 on 2022-01-04 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='branch_name',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='name',
        ),
    ]
