# Generated by Django 4.0 on 2022-01-04 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_leave_branch_name_remove_leave_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='branch_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customuser'),
        ),
    ]
